name: dsa-ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '>= 1.19'
   
    - name: Build Go
      run: cd go-repo && go build cmd/main.go

    - name: Execute Go
      run: cd go-repo && ./main

    - name: Setup python3
      uses: actions/setup-python@v4

    - name: Execute python
      run: python3 python-repo/cmd.py

