name: dsa-ci


on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up go
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '>= 1.19'
   
    - name: Build Go
    - run: cd go-repo && go build cmd/main.go

    - name: Execute Go
    - run: cd go-repo && ./main

